### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/bibxml-to-relaton-mapping#2]
@ronaldtse, I assume the following is true:

1. This repository will not contain mappings, only the script to generate mappings. 
2. The mappings in question concern legacy xml2rfc path feature of BibXML service.
3. This mappings in question are only for NIST dataset.

If this is correct, let’s rename this repository to `xml2rfc-path-mapper-nist`.

We need to create a repository to contain actual xml2rfc mappings, for all subdirectories, and the name clashes with this one.

**Comment by ronaldtse** [comment]
Yes to all points. Repo name changed.

**Comment by ronaldtse** [comment]
@strogonoff are you planning to add other repos for mapping scripts for other datasets? I assume you will have one new repo for the resulting mapping data.
